### ISSUE TITLE
`TypeError: Object of type int32 is not JSON serializable` when use `--out_type json`

### ISSUE THREAD

**Issue by Isuxiz** [modelscope/3D-Speaker#172]
当规定输出格式为 json 时会报错

`python speakerlab/bin/infer_diarization.py --wav ./test.wav --out_dir . --out_type json`

```
Traceback (most recent call last):
  File "/yyy/miniconda3/envs/asr/lib/python3.12/site-packages/torch/multiprocessing/spawn.py", line 75, in _wrap
    fn(i, *args)
  File "/xxx/3D-Speaker/speakerlab/bin/infer_diarization.py", line 524, in main_process
    diarization.save_diar_output(out_file, wav_id)
  File "/xxx/3D-Speaker/speakerlab/bin/infer_diarization.py", line 448, in save_diar_output
    json.dump(out_json, f, indent=2)
  File "/yyy/miniconda3/envs/asr/lib/python3.12/json/__init__.py", line 179, in dump
    for chunk in iterable:
                 ^^^^^^^^
  File "/yyy/miniconda3/envs/asr/lib/python3.12/json/encoder.py", line 432, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/yyy/miniconda3/envs/asr/lib/python3.12/json/encoder.py", line 406, in _iterencode_dict
    yield from chunks
  File "/yyy/miniconda3/envs/asr/lib/python3.12/json/encoder.py", line 406, in _iterencode_dict
    yield from chunks
  File "/yyy/miniconda3/envs/asr/lib/python3.12/json/encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "/yyy/miniconda3/envs/asr/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type int32 is not JSON serializable
```

看起来是 3D-Speaker/speakerlab/bin/infer_diarization.py line 448 处 `json.dump` 前没有把数据类型转回 built-in 导致的

**Comment by wanghuii1** [comment]
Thanks. It has been fixed.
