### ISSUE TITLE
ModuleNotFoundError: No module named 'numpy._core'  

### ISSUE THREAD

**Issue by lightandblue** [modelscope/3D-Speaker#174]
run_audio.sh Stage5: Perform clustering and postprocessing, and output sys rttms...                                                                                                          [INFO] Start clustering...                                                                                                                                                                   
[INFO] Start clustering...                                                                                                                                                                  
 [INFO] Start clustering...                                                                                                                                                                  
 [INFO] Start clustering...                                                                                                                                                                   
Traceback (most recent call last):                                                                                                                                                             
File "local/cluster_and_postprocess.py", line 122, in <module>                                                                                                                                 main()                                                                                                                                                                                     
File "local/cluster_and_postprocess.py", line 116, in main                                                                                                                                     audio_only_func(local_wav_list, args.audio_embs_dir, args.rttm_dir, config)                                                                                                                File "local/cluster_and_postprocess.py", line 59, in audio_only_func                                                                                                                           stat_obj = pickle.load(f)                                                                                                                                                                ModuleNotFoundError: No module named 'numpy._core'                                                                                                                                           Traceback (most recent call last):                                                                                                                                                            
 File "local/cluster_and_postprocess.py", line 122, in <module>                                                                                                                                 main()                                                                                                                                                                                     
File "local/cluster_and_postprocess.py", line 116, in main                                                                                                                                     audio_only_func(local_wav_list, args.audio_embs_dir, args.rttm_dir, config)                                                                                                                File "local/cluster_and_postprocess.py", line 59, in audio_only_func                                                                                                                           stat_obj = pickle.load(f)                                                                                                                                                                ModuleNotFoundError: No module named 'numpy._core'    
我在跑speaker-diarization的run_audio.sh的stage5时候，会遇到有关numpy的报错,
你们推荐numpy>=1.20.0,<1.24，我的numpy版本为1.23.5满足要求，我尝试过其他版本的numpy都不能成功运行，请问有什么解决办法吗

**Comment by wanghuii1** [comment]
可能是环境出了问题，可以pip install --force-reinstall numpy==1.23.5重装numpy，如果还不行可以重新另装一个conda环境试试

**Comment by lightandblue** [comment]
> Collaborator
我这个环境是新创建的，reinstall也不行
